
model:
  target: models.classifier.Classifier
  params:
    data_dir: "/home/akshay/Documents/cse_sem_7/conxai_assignment/cloned/stage-classification/data"
    image_size: &IMG_SIZE 150
    channels: &IMG_CHANNELS 3
    num_classes: &NUM_CLASSES 7
    batch_size: 16 
    max_tsteps: 10 #1e05
    learning_rate: 1.0e-3
    loss_type: "cross_entropy"
    task: 2
    nn_model:
      target: models.lstm.LSTMModel
      params:
        input_size: 67500 # 3*150*150
        hidden_size: 128
        num_layers: 2
        num_classes: *NUM_CLASSES