
model:
  target: models.classifier_t1.Classifier
  params:
    data_dir: ../data
    image_size: &IMG_SIZE 150
    channels: &IMG_CHANNELS 3
    num_classes: &NUM_CLASSES 7
    batch_size: 16 
    max_tsteps: 10e3
    learning_rate: 1.0e-3
    loss_type: "cross_entropy"
    nn_model:
      target: models.cnn.CNNClassification
      params:
        input_channels: *IMG_CHANNELS
        num_classes: *NUM_CLASSES